// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in todogql/ent/runtime.go

const (
	Version = "v0.10.2-0.20220626120058-e8bf1d1cbdb6"           // Version of ent codegen.
	Sum     = "h1:cqSZt+0iJxiQsQDsdrhhVHhjQwk6q8vpIIqW/k4C/l4=" // Sum of ent codegen.
)
